### ISSUE TITLE
Support for metadata with leading XML comment

### ISSUE THREAD

**Issue by relaxnow** [aerialship/lightsaml#34]
Trying to load metadata from: https://engine.surfconext.nl/authentication/idp/metadata yields the following error:
```
Catchable Fatal Error: Argument 1 passed to 
AerialShip\LightSaml\Model\Metadata\EntityDescriptor::loadFromXml() 
must be an instance of DOMElement, instance of DOMComment given, called in 
/vagrant/vendor/aerialship/saml-sp-bundle/src/AerialShip/SamlSPBundle/Config/EntityDescriptorFileProvider.php 
on line 91 and defined in 
/vagrant/vendor/aerialship/lightsaml/src/AerialShip/LightSaml/Model/Metadata/EntityDescriptor.php 
line 156
```
It appears to fail at the leading XML comment which is required by eduGain.

**Comment by tmilos** [comment]
A new version of lightsaml is available in https://github.com/lightSAML/lightSAML 
Have copied this issue there to unsure it being fixed in new version too, and regarding this old aerialship version made issue in relevant repository https://github.com/aerialship/SamlSPBundle/issues/109
