### ISSUE TITLE
Is there any detailed documentation available for beginners?

### ISSUE THREAD

**Issue by sithik** [aerialship/lightsaml#36]
LightSaml matches my requirements straight forward. But the steps to install and use the classes will be highly helpful for beginners.

**Comment by tmilos** [comment]
A [new lightsaml version](https://packagist.org/packages/lightsaml/lightsaml) is available and a cookbook is compiled with some examples of usage http://www.lightsaml.com/LightSAML-Core/Cookbook/. Maybe that can help you start with it. Please feel free to open an issue on new [lightsaml/lightsaml issues](https://github.com/lightSAML/lightSAML/issues) and explain what kind of document would be helpful.
