### ISSUE TITLE
How to really parse SAMLResponse?

### ISSUE THREAD

**Issue by tishma** [aerialship/lightsaml#46]
I totally bought the idea of dumping 'simplesamlphp', as it is anything but simple.
I was so happy to see the example of parsing a SAML response, but after a test run that returns nothing, and a second look, it's unclear how to feed it with metadata.xml file so it can properly do the decryption.

I've seen another issue about the docs that will hopefully improve with v2. I'd love to participate by challenging authors to think about library consumers as people who would rather talk in terms of SSO and authentication rather than going deep into SAML implementation and concepts..

**Comment by tmilos** [comment]
Hello @tishma 
Thanks, glad you find it interesting. Can you please give some clue on what kind of documentation will be helpful to you? Can you paste that demo code you tried and it didn't work?

Note that there's a new version of lightsaml in it's own organization at https://github.com/lightsaml. Here's the [lightsaml cookbook](http://www.lightsaml.com/LightSAML-Core/Cookbook/). Did you meant something like that? If you find something else will improve the docs and make it more usable to users, please help us and describe what kind of docs should be made.

Please [report issues on the new version](https://github.com/lightSAML/lightSAML/issues), I'm closing this one.
