### ISSUE TITLE
Relation to lightsaml/lightsaml

### ISSUE THREAD

**Issue by cb8** [aerialship/lightsaml#48]
Is [lightSAML](https://github.com/lightSAML/lightSAML) the official successor to `aerialship/lightsaml`? If so, should we add a small notice and mark this Composer package as deprecated?

**Comment by tmilos** [comment]
Yes, http://www.lightsaml.com/ is official successor to aerialship/lightsaml, but still in beta. I'm finishing small details for the release, and preparing the announcement. It would be great if you could contribute with suggested. 

Can you please explain how can a composer package be marked as deprecated?

**Comment by cb8** [comment]
Alright, in that case I will start with `lightsaml/lightsaml`.

As far as I know, there should be a button on [packagist.org](https://packagist.org/) to mark the package as "abandoned". You should be able to set the new package as successor.

Example of an abondened package: [guzzle/http](https://packagist.org/search/?q=guzzle%2Fhttp)

**Comment by benreic** [comment]
I've been implementing a SAML SSO solution using the `aerialship/lightsaml` library, but I need support for the SessionNotOnOrAfter attribute, which it looks like you've implemented in `lightsaml/lightsaml`. Is the new library close to being 1.0, and could I start using it in projects now?

**Comment by tmilos** [comment]
It just has been tagged 1.0.0. Feel free to use it

**Comment by benreic** [comment]
Thank you so much!

**Comment by benreic** [comment]
I ported my code that was using the `aerialship/lightsaml` library to use the new one. I had the previous library working, using Salesforce.com as my IdP. When using the new library, I'm getting my AuthnRequest rejected by Salesforce, with an "Invalid Signature" error. I've compared the AuthnRequests generated by the old library and the new one, and they're nearly identical, except for the missing "samlp:" on the NameIDPolicy node, and a couple xml attributes in a different order.

Did the AuthnRequest signing workflow change in the new library? I've pasted the relevant code here, if you see something obviously wrong that would be a big help, thanks

```
		$authnRequest  =  new Protocol\AuthnRequest( );
		$authnRequest->setID( $requestId );
		$authnRequest->setDestination( $this->getIdPDestinationUrl( $idpED, $settings->requestBinding ) );
		$authnRequest->setIssueInstant( $instant );
		$authnRequest->setAssertionConsumerServiceURL( $this->getSPAssertionConsumerServiceUrl( $spED, $settings->requestBinding ) );
		$authnRequest->setProtocolBinding( $settings->requestBinding );
		$authnRequest->setIssuer( new Assertion\Issuer( $spED->getEntityID( ) ) );
		$nameIdPolicy  =  new Protocol\NameIDPolicy( );
		$nameIdPolicy->setFormat( $settings->nameFormat );
		$nameIdPolicy->setAllowCreate( true );
		$authnRequest->setNameIDPolicy( $nameIdPolicy );

		// Sign the request so the IdP can verify its authenticity.
		$cert  =  $this->getSPSigningCertificate( ); // this is a string value
		$privateKey  =  $this->getSPPrivateKey( ); // this is a string value
		$x509  =  new Credential\X509Certificate( );
		$x509->loadPem( $cert );
		$key =  Credential\KeyHelper::createPrivateKey( $privateKey, $this->privateKeyPassphrase );
		$sigWriter  =  new XmlDSig\SignatureWriter( $x509, $key );
		$authnRequest->setSignature( $sigWriter );
		$this->debugLogAuthnRequest( $authnRequest );
		return $authnRequest;
```

**Comment by tmilos** [comment]
@benreic This is way out of the initial topic of the issue. If this will expand even further, please open a new issue. 

I don't see a problem with the code you wrote. Note that you yourself could verify the signature of the ``AuthnRequest`` you made: serialize created AuthnRequest to xml string, so it gets signed, then create a new AuthnRequest instance and deserialize that xml string to it, so it has SignatureRead instance in place of it's signature, load your public key and call validate method on the signature. 

Beside, you could check if you're using the same key pair you registered with IDP, and if your entity id, binding type, and assertion consumer service url is same as those registered with IDP.

I'm closing the issue, if there's anything more needed, please open a new issue, and provide old working and new non-working AuthnRequest xml, and your metadata xml registered with IDP.
